name: CI / Build & Push Docker Images

# Se ejecuta cada vez que hagas push a main (ajusta branch si necesitas)
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # para poder publicar en GitHub Container Registry
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU (para emular multiplataforma si quieres)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Frontend: build estático ---
      - name: Build frontend (Vite)  
        working-directory: ./gestor_de_recursos_fe
        run: |
          # instalamos deps y compilamos // en runner x86_64 no busca módulos ARM
          npm ci
          npm run build

      # --- Backend: opcionalmente podrías ejecutar tests Django ---
      - name: Run backend tests (opcional)
        working-directory: ./gestor_de_recursos
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pytest -q

      # --- Inicia sesión en GitHub Container Registry ---
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Construir y publicar imagen del backend ---
      - name: Build & push Django backend image
        uses: docker/build-push-action@v4
        with:
          context: ./gestor_de_recursos
          file: ./gestor_de_recursos/Dockerfile
          platforms: linux/amd64         # construye en amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mi-backend:latest
            ghcr.io/${{ github.repository_owner }}/mi-backend:${{ github.sha }}

      # --- Construir y publicar imagen del frontend (Nginx + dist) ---
      - name: Build & push React frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./gestor_de_recursos_fe
          file: ./gestor_de_recursos_fe/Dockerfile
          platforms: linux/amd64         # le indicamos build en x86_64
          build-args: |
            # Si tu Dockerfile requiere algun ARG, ponlo aquí
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mi-frontend:latest
            ghcr.io/${{ github.repository_owner }}/mi-frontend:${{ github.sha }}

      - name: Image digest info
        run: |
          echo "Backend image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/mi-backend:latest"
          echo "Frontend image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/mi-frontend:latest"
